In [42]:
import pandas as pd

df = pd.read_csv('data/dst-3.0_16_1_hh_database.csv', sep=';')

# display(df.head())

def education_class(elem):
    elem=elem.lower()
    if 'неоконченное высшее' in elem:
        elem = 'неоконченное высшее'
    elif 'высшее' in elem:
        elem = 'высшее'
    if 'среднее специальное' in elem:
        elem = 'среднее специальное'
    elif 'среднее' in elem:
        elem = 'среднее'    
    return elem

df['Образование'] = df['Образование и ВУЗ'].apply(education_class)

# display(df[df['Образование'] == 'среднее'].head(5))
df['Образование']=df['Образование'].astype('category')
# df.info()
# df.info()
# df['Образование'].cat.categories

df['Пол'] = df['Пол, возраст'].apply(
    lambda x: 'М' if 'Мужчина' in x else 'Ж'
    )

df['Пол'].value_counts()

df['Возраст'] = df['Пол, возраст'].apply(lambda x: int(x.split(' ')[3]) )
df.head()

def exprns(elem):
    try:
        counter = 0
        elem = elem.split(' ')
        if 'го' or 'ле' in elem[3]:
            counter += int(elem[2])*12
        
        if 'мес' in elem[3]:
            counter += int(elem[2])
        
        if 'мес' in elem[5]:
            counter += int(elem[4])
        
        return counter
    
    except:
        return None
    
df['Опыт работы (месяц)'] = df['Опыт работы'].apply(exprns)

df[df['Опыт работы (месяц)'] == 'NaN'].head()          



def city_filling(elem):
    million_cities = ['Новосибирск', 'Екатеринбург', 'Нижний Новгород', 
                  'Казань', 'Челябинск', 'Омск', 'Самара', 
                  'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 
                  'Воронеж', 'Волгоград' 
                  ]
    
    elem = elem.split(',')
    city = ''

    if 'Москва' in elem[0] or 'Санкт-Петер' in elem[0]:
        city = elem[0]
    elif elem[0] in million_cities:
        city = 'город-миллионник'
    else:
        city = 'другие'
        
    return city

df['Город'] = df['Город, переезд, командировки'].apply(city_filling)

df.head()


# Функция для вычленения элемента тематики перезда и его обработка

def relocate(elem):
    elem = elem.split(',')
    item_relocate = 'переезд'

    for item_relocate in elem:
        if item_relocate in elem:
            if 'не' in elem:
                return False
            else:
                return True
            

# Функция для вычленения элемента тематики командировки и его обработка,

def bis_trip(elem):
    elem = elem.split(',')
    item_bis_trip = 'коман'

    if item_bis_trip in elem[-1]:
        if 'не' in elem[-1]:
            return False
        else:
            return True 
    else:
        return False 


df['Готовность к переезду'] = df['Город, переезд, командировки'
                                 ].apply(relocate)
df['Готовность к командировкам'] = df['Город, переезд, командировки'
                                      ].apply(bis_trip)


df.head()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто,Образование,Пол,Возраст,Опыт работы (месяц),Город,Готовность к переезду,Готовность к командировкам
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль,неоконченное высшее,М,39,202.0,другие,True,False
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано,высшее,М,60,233.0,другие,True,True
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано,среднее специальное,Ж,36,123.0,другие,True,False
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано,высшее,М,38,225.0,другие,True,True
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано,высшее,Ж,26,67.0,Москва,True,True

In [40]:
a = 'Москва , не готова к переезду , готова к кома..'

a = a.split(',')
a
item_relocate = 'переезд'

for elem in a:
    if item_relocate in elem:
        if 'не' in elem:
            print('False')
        else:
            print('True')

item_bis_trip = 'коман'

if item_bis_trip in a[-1]:
    if 'не' not in a[-1]:
        print('True')
    else:
        print('False') 
else:
    print('Flase nono') 

# for elem in a:
#     if item_bis_trip not in elem:
#         print('Flase nono')
        
#     else:
#         if item_bis_trip in elem:
#             if 'не' not in elem:
#                 print('True')
#             else:
#                 print('False')



# if item in a:
#     print(a)
# print(b)

False
Flase nono

In [10]:
a = 'Москва , не готова к переезду , готова к коман..'

a = a.split(',')

million_cities = ['Новосибирск', 'Екатеринбург', 'Нижний Новгород', 
                'Казань', 'Челябинск', 'Омск', 'Самара', 
                'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 
                'Воронеж', 'Волгоград' 
                ]

if 'Москва' in a[0] or 'Санкт-Петер' in a[0]:
        print('Yep', a[0])
elif a[0] in million_cities:
        print('город-миллионник')
else:
        print('другие')

print(a[0])

type(a)

Yep Москва
Москва

list

In [31]:
a = 'Опыт работы 10 месяцев Август 2018 — по насто...'


def exprns(elem):
    try:
        counter = 0
        elem = elem.split(' ')
        if ('го' or 'ле') in elem[3]:
            counter += int(elem[2])*12
            print('1 ', counter)
            print(elem[3])
        
        if 'мес' in elem[3]:
            counter += int(elem[2])
            print('2 ', counter)
        
        if 'мес' in elem[5]:
            counter += int(elem[4])
            print('3 ', counter)
        
        return counter
    except:
        return None

exprns(a)

2  10

10